# Generated by Django 2.0.5 on 2018-06-02 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=20, null=True)),
                ('fees', models.FloatField(null=True)),
                ('paid_on', models.DateTimeField(null=True)),
                ('fees_receipt', models.FileField(help_text='upload pdf file less than 2mb', null=True, upload_to='')),
                ('is_fees_paid', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('caterer_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('is_veg', models.BooleanField(default=True)),
                ('is_nonVeg', models.BooleanField(default=False)),
                ('gender_intake', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('intake', models.IntegerField(null=True)),
                ('is_full', models.BooleanField(default=False)),
                ('present_strength', models.IntegerField(default=0)),
                ('manager_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
